/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2eddandresimerycarlosgonzalez;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlo
 */
public class BuscarReserva extends javax.swing.JFrame {
    private static VentanaInicio inicio;
    private Reserva reserva;
    private Estado estado;
    /**
     * Creates new form BuscarReserva
     */
    public BuscarReserva(VentanaInicio inicio) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        this.inicio = inicio;
        this.reserva = null;
        this.estado = null;
    }
    public VentanaInicio getInicio() {
        return this.inicio;
    }
    public Reserva getReserva() {
        return this.reserva;
    }

    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Estado getEstado() {
        return this.estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldCedulaUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonBCheckIn = new javax.swing.JButton();
        jLabelBNombre = new javax.swing.JLabel();
        jLabelBApellido = new javax.swing.JLabel();
        jLabelBEmail = new javax.swing.JLabel();
        jLabelBGenero = new javax.swing.JLabel();
        jLabelBTipo = new javax.swing.JLabel();
        jLabelBCelular = new javax.swing.JLabel();
        jLabelBLlegada = new javax.swing.JLabel();
        jLabelBSalida = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(612, 406));
        setMinimumSize(new java.awt.Dimension(612, 406));
        setSize(new java.awt.Dimension(612, 406));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(612, 406));
        jPanel1.setPreferredSize(new java.awt.Dimension(612, 406));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCedulaUser.setBackground(new java.awt.Color(0, 0, 0));
        jTextFieldCedulaUser.setForeground(new java.awt.Color(255, 153, 0));
        jTextFieldCedulaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaUserActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCedulaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 120, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CHECK-IN HOTEL BOOKING");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 620, 70));

        jButtonVolver.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVolver.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 153, 0));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jButtonBCheckIn.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBCheckIn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonBCheckIn.setForeground(new java.awt.Color(255, 153, 0));
        jButtonBCheckIn.setText("Check-In");
        jButtonBCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBCheckInActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        jLabelBNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBNombre.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 340, 20));

        jLabelBApellido.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBApellido.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelBApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 340, 20));

        jLabelBEmail.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBEmail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelBEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 360, 20));

        jLabelBGenero.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBGenero.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelBGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 340, 20));

        jLabelBTipo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBTipo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelBTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 220, 20));

        jLabelBCelular.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBCelular.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelBCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 240, 20));

        jLabelBLlegada.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBLlegada.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelBLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 230, 20));

        jLabelBSalida.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBSalida.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabelBSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 240, 20));

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("<html>\nIngrese la cedula del cliente:<br>\nNombre:<br>\nApellido:<br>\nEmail:<br>\nGenero:<br>\nTipo de Habitacion:<br>\nTelefono Celular:<br>\nFecha de Llegada:<br>\nFecha de Salida:\n<html>\n");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 620, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2eddandresimerycarlosgonzalez/fondorecepcion.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String cedula = this.jTextFieldCedulaUser.getText(); 
        if (cedula.matches("\\d+")) {
            Integer cedula_num = Integer.parseInt(this.jTextFieldCedulaUser.getText());
            Reserva reserva = getInicio().getArbol_R().searchReservaCedula(getInicio().getArbol_R().getRoot(), cedula_num);
            if (reserva != null) {
                jLabelBNombre.setText(reserva.getCliente().getNombre());
                jLabelBNombre.setText(reserva.getCliente().getNombre());
                jLabelBApellido.setText(reserva.getCliente().getApellido());
                jLabelBEmail.setText(reserva.getCliente().getCorreo());
                jLabelBGenero.setText(reserva.getCliente().getGenero());
                jLabelBCelular.setText(reserva.getCliente().getCelular());
                jLabelBLlegada.setText(reserva.getLlegada().getDate() + "/" + reserva.getLlegada().getMonth() + "/" + reserva.getLlegada().getYear());
                jLabelBSalida.setText(reserva.getSalida().getDate() + "/" + reserva.getSalida().getMonth() + "/" + reserva.getSalida().getYear());
                this.setReserva(reserva);
            } else {
                new JOptionPane().showMessageDialog(null, "La cedula que ha ingresado no tiene una reserva.");
            }   
        } else {
            new JOptionPane().showMessageDialog(null, "La cédula debe ser unicamente números. (sin \".\")");
            getInicio().setVisible(true);
            this.dispose();
        }
//        try { 
//            Integer.parseInt(cedula); 
//            System.out.println(cedula + " is a valid integer");
//            int num_cedula = Integer.parseInt(cedula);
//            if (getInicio().getArbol_R().searchReservaCedula(getInicio().getArbol_R().getRoot(), num_cedula )!= null){
//                reserva = getInicio().getArbol_R().searchReservaCedula(getInicio().getArbol_R().getRoot(), num_cedula);
//                jLabelBNombre.setText(reserva.getCliente().getNombre());
//                jLabelBNombre.setText(reserva.getCliente().getNombre());
//                jLabelBApellido.setText(reserva.getCliente().getApellido());
//                jLabelBEmail.setText(reserva.getCliente().getCorreo());
//                jLabelBGenero.setText(reserva.getCliente().getGenero());
//                jLabelBCelular.setText(reserva.getCliente().getCelular());
//                jLabelBLlegada.setText(reserva.getLlegada().getDate() + "/" + reserva.getLlegada().getMonth() + "/" + reserva.getLlegada().getYear());
//                jLabelBSalida.setText(reserva.getSalida().getDate() + "/" + reserva.getSalida().getMonth() + "/" + reserva.getSalida().getYear());
//                this.setReserva(reserva);
//            }else{
//                JOptionPane.showMessageDialog(null, "Ïngrese de nuevo la cedula");
//            }
//            
//            
//            
//        }catch (NumberFormatException e){
//            
//            System.out.println(cedula + " is not a valid integer"); 
//            
//        } 
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldCedulaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaUserActionPerformed

    private void jButtonBCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBCheckInActionPerformed
        Reserva reserva = getReserva();
        NodoArbol<Habitacion> habitacion = getInicio().getArbol_H().searchHabitacionVaciaTipo(getInicio().getArbol_H().getRoot(), reserva.getTipo());
        Estado estado = new Estado(habitacion.getElement(), reserva.getCliente(),reserva.getLlegada());
        this.setEstado(estado);
        getInicio().getHash().addEstado(estado);
        habitacion.getElement().setEstado(estado);
        
        getInicio().getArbol_R().deleteReserva2(getInicio().getArbol_R().getRoot(), reserva);
//      insertar Joption pane con la habitacion que se le asigno a la persona.
        new JOptionPane().showMessageDialog(null, "El cliente ha sido hospedado exitosamente en la habitacion #" + habitacion.getElement().getNum());
        this.inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBCheckInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarReserva(inicio).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBCheckIn;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBApellido;
    private javax.swing.JLabel jLabelBCelular;
    private javax.swing.JLabel jLabelBEmail;
    private javax.swing.JLabel jLabelBGenero;
    private javax.swing.JLabel jLabelBLlegada;
    private javax.swing.JLabel jLabelBNombre;
    private javax.swing.JLabel jLabelBSalida;
    private javax.swing.JLabel jLabelBTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCedulaUser;
    // End of variables declaration//GEN-END:variables
}
