/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2eddandresimerycarlosgonzalez;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlo
 */
public class HistorialHabitacion extends javax.swing.JFrame {
    private static VentanaInicio inicio;
    /**
     * Creates new form HistorialHabitacion
     */
    public HistorialHabitacion(VentanaInicio inicio) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        this.inicio = inicio;
    }
    
    public VentanaInicio getInicio() {
        return this.inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelActual = new javax.swing.JLabel();
        listClientes = new java.awt.List();
        jLabelTipo = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(612, 406));
        setMinimumSize(new java.awt.Dimension(612, 406));
        setResizable(false);
        setSize(new java.awt.Dimension(612, 406));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(612, 406));
        jPanel1.setMinimumSize(new java.awt.Dimension(612, 406));
        jPanel1.setPreferredSize(new java.awt.Dimension(612, 406));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelActual.setForeground(new java.awt.Color(255, 153, 0));
        jLabelActual.setText("jLabelActual");
        jPanel1.add(jLabelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 370, 30));
        jPanel1.add(listClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 610, 200));

        jLabelTipo.setBackground(new java.awt.Color(255, 153, 0));
        jLabelTipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipo.setOpaque(true);
        jPanel1.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 80, 30));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        jButtonVolver.setBackground(new java.awt.Color(255, 153, 0));
        jButtonVolver.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVolver.setText("Volver a Inicio");
        jButtonVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 367, 190, 40));

        jTextFieldNumero.setBackground(new java.awt.Color(255, 153, 0));
        jTextFieldNumero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNumero.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNumero.setText("Número");
        jPanel1.add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 110, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("<html><br>\n&nbsp Ingrese el Numero de Habitacion:<br><br><br>\n&nbsp Historial de clientes:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Tipo de Habitacion:<br><br>\n<html>");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 620, 320));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hotel Booking Historial");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2eddandresimerycarlosgonzalez/fondorecepcion.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String numero_string = this.jTextFieldNumero.getText();
        
        if (numero_string.matches("\\d+")) {
            this.listClientes.clear();
            Integer numero = Integer.parseInt(numero_string);
            Habitacion habitacion = getInicio().getArbol_H().searchHabitacionNum(getInicio().getArbol_H().getRoot(), numero);
            this.jLabelTipo.setText(habitacion.getTipo());
            if (habitacion.getEstado() != null) {
                this.jLabelActual.setText("Cliente Actual: " + habitacion.getEstado().getCliente().getNombre() + " " + habitacion.getEstado().getCliente().getApellido());
            }
            if (habitacion.getHistoricos() != null) {
                Nodo<Historico> pointer = habitacion.getHistoricos().getHead();
                while (pointer != null) {
                    Cliente cliente = pointer.getElement().getCliente();
                    this.listClientes.add("C.I: " + cliente.getCedula() + "| " + cliente.getNombre() + " " + cliente.getApellido() + " |Cel: " + cliente.getCelular() + " |Correo: " + cliente.getCorreo() + " |Genero: " + cliente.getGenero());
                    pointer = pointer.getNext();
                }
            }
            
            
        } else {
            new JOptionPane().showMessageDialog(null, "La Habitacion no ha sido encontrada.");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialHabitacion(inicio).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelActual;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNumero;
    private java.awt.List listClientes;
    // End of variables declaration//GEN-END:variables
}
